FROM docker.io/library/alpine:${com.io7m.oci.versionAlpine}
FROM docker.io/library/eclipse-temurin:${com.io7m.oci.versionTemurin}

ENV PATH="/azeno/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/java/openjdk/bin"
ENV AZENO_HOME="/azeno"

COPY azeno /azeno

LABEL "org.opencontainers.image.authors"="Mark Raynsford"
LABEL "org.opencontainers.image.description"="Digital asset system"
LABEL "org.opencontainers.image.licenses"="ISC"
LABEL "org.opencontainers.image.source"="https://www.github.com/io7m/azeno"
LABEL "org.opencontainers.image.title"="Azeno"
LABEL "org.opencontainers.image.url"="https://www.io7m.com/software/azeno"
LABEL "org.opencontainers.image.version"="${project.version}"
LABEL "org.opencontainers.image.revision"="${buildNumber}"

ENTRYPOINT ["/azeno/bin/azeno"]
